### PR TITLE
Prefer pkg-config over gpgme-config

### PR DESCRIPTION
**Pull request by sathieu**
See https://bugs.debian.org/1023601 for context.

### CODE REVIEW

**Review by ueno — APPROVED** [review]
Thanks!

**Comment by sathieu** [comment]
Thanks for your quick merge!

**Comment by geor-g** [comment]
Thanks! @ueno Any chance of cutting a new release, including this fix? It would ease fixing this in downstream environments like Debian.

**Comment by ueno** [comment]
Pushed 2.0.22.

**Pull request merged**
