### PR TITLE
Reorganize and update (add 2.6) Rubies in Travis build matrix

### PR DESCRIPTION
**Pull request by skalee**

### CODE REVIEW

**Comment by skalee** [comment]
Also, I propose to not specify PATCH (as in MAJOR.MINOR.PATCH) for Ruby versions in Travis build matrix (i.e. `2.4.3` -> `2.4`, `2.5.0` -> `2.5` etc.). Travis will install the latest available PATCH for given MAJOR.MINOR then.

**Comment by ueno** [comment]
> Also, I propose to not specify PATCH (as in MAJOR.MINOR.PATCH) for Ruby versions in Travis build matrix (i.e. 2.4.3 -> 2.4, 2.5.0 -> 2.5 etc.).

Sounds good to me. Would you like to update the patch along these lines?

**Comment by skalee** [comment]
I've reordered Rubies as well. Rationale is in commit message.

**Comment by ueno** [comment]
Thank you!

**Pull request merged**
